CREATE DATABASE SALE_ANALYSIS_PRJ;
USE SALE_ANALYSIS_PRJ;

SELECT * FROM SALES_DATA_700;

ALTER TABLE SALES_DATA_700
ADD AMOUNT FLOAT;

UPDATE SALES_DATA_700
SET AMOUNT =UNIT_PRICE * UNITS_SOLD;

-- BASIC STATICITS (DESCRIPITIVE ANALYSIS)

-- COUNT OF RECORDS
SELECT COUNT(*) AS CNT
FROM SALES_DATA_700;

--TOTAL REVENUE GENERATION
SELECT SUM (AMOUNT) AS TOTALREVENUE
FROM SALES_DATA_700;
-- TOTAL REVENUE GENERATED 698715

-- PRODUCT WISE REVENUE  
SELECT PRODUCT, SUM(AMOUNT) AS TOTALREVENUE
FROM SALES_DATA_700
GROUP BY PRODUCT;

-- TOTAL NUMBER OF PRODUCTS SOLD

SELECT SUM(UNITS_SOLD) AS PRODUCTSOLD
FROM SALES_DATA_700;
--17778
-- TOTAL NUMBER OF PRODUCT SOLD (PRODUCTWISE)
SELECT PRODUCT, SUM(UNITS_SOLD) AS PRODUCTSOLD
FROM SALES_DATA_700
GROUP BY PRODUCT
ORDER BY PRODUCTSOLD DESC;

-- HIGHEST SOLD PRODUCT IS BISCUITS


--TOP 5 SELLING PRODUCT UNIT WISE
SELECT TOP(5) PRODUCT,SUM(UNITS_SOLD) AS PRODUCTSOLD
FROM SALES_DATA_700
GROUP BY PRODUCT
ORDER BY PRODUCTSOLD;

-- MY SQL
/*
SELECT PRODUCT,SUM(UNITS_SOLD) AS  PRODUCTSOLD
FROM SALES_DATA_700
GROUP BY PRODUCT 
ORDER BY PRODUCTSOLD DESC
LIMIT 5;

*/

-- HIGHEST REVEUNE GENERATING PRODUCT
SELECT TOP(5) PRODUCT,SUM(AMOUNT) AS REVENUESUM
FROM SALES_DATA_700
GROUP BY PRODUCT
ORDER BY REVENUESUM DESC;

-- OIL IS HIGHEST REVENUE GENERATING PRODUCT

-- TIME BASED ANALYSIS

SELECT MONTH(DATE) AS MN FROM SALES_DATA_700;

ALTER TABLE SALES_DATA_700
ADD SALEMONTH INT;

UPDATE SALES_DATA_700
SET SALEMONTH =MONTH(DATE);

SELECT* FROM SALES_DATA_700;

SELECT SALEMONTH,SUM(AMOUNT)AS REVEUNE FROM SALES_DATA_700
GROUP BY SALEMONTH
ORDER BY REVEUNE DESC;

-- HIGHEST SALE OCCURED IN MARCH

SELECT SALEMONTH,PRODUCT,SUM(AMOUNT) AS REVENUE FROM SALES_DATA_700
GROUP BY SALEMONTH,PRODUCT
ORDER BY REVENUE DESC;
